//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.09 at 03:32:53 PM GMT 
//


package ie.gmit.sw.BookingModel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Vehicle Schema
 * 			
 * 
 * <p>Java class for Vehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vehicle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="carRegistration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="carManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carColour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carEngineSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vehicle", propOrder = {
    "carRegistration",
    "carManufacturer",
    "carModel",
    "carColour",
    "carEngineSize"
})
public class Vehicle {

    protected int carRegistration;
    @XmlElement(required = true)
    protected String carManufacturer;
    @XmlElement(required = true)
    protected String carModel;
    @XmlElement(required = true)
    protected String carColour;
    protected int carEngineSize;

    /**
     * Gets the value of the carRegistration property.
     * 
     */
    public int getCarRegistration() {
        return carRegistration;
    }

    /**
     * Sets the value of the carRegistration property.
     * 
     */
    public void setCarRegistration(int value) {
        this.carRegistration = value;
    }

    /**
     * Gets the value of the carManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarManufacturer() {
        return carManufacturer;
    }

    /**
     * Sets the value of the carManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarManufacturer(String value) {
        this.carManufacturer = value;
    }

    /**
     * Gets the value of the carModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * Sets the value of the carModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarModel(String value) {
        this.carModel = value;
    }

    /**
     * Gets the value of the carColour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarColour() {
        return carColour;
    }

    /**
     * Sets the value of the carColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarColour(String value) {
        this.carColour = value;
    }

    /**
     * Gets the value of the carEngineSize property.
     * 
     */
    public int getCarEngineSize() {
        return carEngineSize;
    }

    /**
     * Sets the value of the carEngineSize property.
     * 
     */
    public void setCarEngineSize(int value) {
        this.carEngineSize = value;
    }

}
